
project_id = "njjqwcgoxuxlgaihrwux"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Enable Edge Functions
[functions]
enabled = true

[functions.create-workspace]
verify_jwt = true

[functions.update-workspace-payment]
verify_jwt = true

[functions.check-email]
verify_jwt = false

[functions.invite-user]
verify_jwt = true
