
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://njjqwcgoxuxlgaihrwux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qanF3Y2dveHV4bGdhaWhyd3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NjAwODUsImV4cCI6MjA1OTAzNjA4NX0.Q5fRbFNfOdiysE1eyRhNUr_HOtpoGkBgeVuFxRqepko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
